name: CI/CD for Cafe frontend code

on: 
    workflow_dispatch: 
    push: 
        branches: 
            - main
    pull_request:
        branches:
            - main


jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the code
              uses: actions/checkout@v3

            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Install all dependence
              run: npm install

            - name: Run the test
              run: npm run test

            - name: Run the build
              run: npm run build

    lint:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout the code
              uses: actions/checkout@v3

            - name: Install Nodejs
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Insall dependence
              run: npm install

            - name: Run the lint
              run: npm run lint



